// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice.Data;

namespace Practice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practice.Models.CompanyModel", b =>
                {
                    b.Property<int>("comapny_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("comapny_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("company_founded_on")
                        .HasColumnType("datetime2");

                    b.HasKey("comapny_id");

                    b.ToTable("Componies");
                });

            modelBuilder.Entity("Practice.Models.EmployeeModel", b =>
                {
                    b.Property<string>("empno")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firts_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hire_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("empno");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
